In [1]:
import pandas as pd
import numpy as np
import os

In [85]:
file="/TrainingWiDS2021.csv"
path=os.getcwd()+file #get common work directory

In [86]:
path

'/Users/skyli/Documents/kaggle/TrainingWiDS2021.csv'

In [87]:
dat = pd.read_csv(path)

In [88]:
dat = dat.drop(['Unnamed: 0'],axis =1)

In [89]:
dat.shape

(130157, 180)

In [90]:
y=dat['diabetes_mellitus']

In [91]:
#drop id, y
dat = dat.drop(columns=['encounter_id','hospital_id', 'icu_id','diabetes_mellitus'])

In [92]:
dat.dtypes.unique()

array([dtype('float64'), dtype('int64'), dtype('O')], dtype=object)

In [124]:
#separate the numeric and categorical

num = dat.select_dtypes(include=['float64','int64'])
cat = dat.select_dtypes(include=['O'])

In [135]:
dat.isnull().sum()[dat.isnull().sum()>0]

age                       4988
bmi                       4490
ethnicity                 1587
gender                      66
height                    2077
                         ...
h1_arterial_ph_min      107849
h1_arterial_po2_max     107445
h1_arterial_po2_min     107445
h1_pao2fio2ratio_max    113397
h1_pao2fio2ratio_min    113397
Length: 160, dtype: int64

In [154]:
dat1=dat.copy()

In [155]:
#missing = dat.isnull().sum()

In [160]:
#get the last three digit of the column name
#if column name ends with min or max the fill na 0

def fillna_all(dat):
    for i in dat.columns:
        
        if dat[i].dtype in ['float64','int64']:
        
            #fill max,min variables
        
            if i[-3:] == 'max' or i[-3:] == 'min':
                dat.loc[:,(i)].fillna(0,inplace = True)
        
            #fill age,bmi,weight,height
        
            if i in ['age','bmi','weight','height']:
                dat.loc[:,(i)] = dat[i].fillna(dat[i].mean())
        
        
            #fill all the apache related variables
        
            if i[-6:] == 'apache' or i[:6] == 'apache':
                dat.loc[:,(i)] = dat[i].fillna(0)
                
        else:
            dat.loc[:,(i)] = dat[i].fillna('Unknown')
            
            
    return(dat)
    #test:  dat_test1['h1_pao2fio2ratio_max'].isnull().sum()

In [161]:
fillna_all(dat1)

,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,icu_stay_type,icu_type,...,h1_arterial_po2_min,h1_pao2fio2ratio_max,h1_pao2fio2ratio_min,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
0,68.0,22.732803,0,Caucasian,M,180.3,Floor,Floor,admit,CTICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
1,77.0,27.421875,0,Caucasian,F,160.0,Floor,Floor,admit,Med-Surg ICU,...,51.0,51.0,51.0,0,0,0,0,0,0,0
2,25.0,31.952749,0,Caucasian,F,172.7,Emergency Department,Accident & Emergency,admit,Med-Surg ICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
3,81.0,22.635548,1,Caucasian,F,165.1,Operating Room,Operating Room / Recovery,admit,CTICU,...,265.0,337.0,337.0,0,0,0,0,0,0,0
4,19.0,29.110260,0,Caucasian,M,188.0,Unknown,Accident & Emergency,admit,Med-Surg ICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130152,50.0,29.287256,0,Caucasian,M,175.3,Emergency Department,Accident & Emergency,admit,Cardiac ICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
130153,79.0,29.653433,0,Caucasian,F,162.6,Direct Admit,Accident & Emergency,admit,MICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
130154,73.0,32.265371,0,African American,M,177.8,Emergency Department,Accident & Emergency,admit,Cardiac ICU,...,163.0,163.0,163.0,0,0,0,0,0,0,0
130155,81.0,24.408579,0,Caucasian,M,185.4,Emergency Department,Accident & Emergency,admit,Med-Surg ICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0
130156,35.0,30.132358,0,African American,M,182.9,Emergency Department,Accident & Emergency,admit,MICU,...,0.0,0.0,0.0,0,0,0,0,0,0,0

In [162]:
dat1.isnull().sum()[dat1.isnull().sum()>0]

Series([], dtype: int64)

In [ ]:
#one hot encoding